export { default as Texts } from "./texts";
export { default as Client } from "./client";
export { default as Info } from "./info";
export { default as Inbody } from "./inbody";
export { default as Photo } from "./photo";
export { default as Ai } from "./ai";
export { default as StartBtn } from "./start-btn";
export { default as UpcomingTime } from "./upcoming-time";
export { default as InbodyGraph } from "./inbody-graph";
