import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
    title: "365MC 키오스크",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="kr" className="isHidedScrollBar">
            <body>{children}</body>
        </html>
    );
}
